name: E2E Tests Custom

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''
      browsers:
        description: 'Comma-separated list of browsers to execute tests against (e.g., chrome,firefox)'
        default: 'chrome,firefox'
jobs:
  preprocess:
    runs-on: ubuntu-latest
    outputs:
      selected: ${{ steps.process.outputs.selected }}
    steps:
      - name: Process Browser Input
        id: process
        run: |
          browsers="${{ github.event.inputs.browsers }}"
          echo "Selected browsers: $browsers"
          echo "::set-output name=selected::$browsers"

  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    needs: preprocess
    if: contains(needs.preprocess.outputs.selected, 'chrome')
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="chrome" -DexecutionAddress="local" -DtargetOperatingSystem="LINUX" -DheadlessExecution="true" -DwhenToTakePageSourceSnapshot="FailuresOnly" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -Dtest="${{ github.event.inputs.testsPath }}"
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Allure
          path: "allure-report/*_AllureReport.html"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Summary
          path: "execution-summary/ExecutionSummaryReport_*.html"
#      - name: Publish Report
#        continue-on-error: true
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Tests Report Chrome_Linux
#          path: 'target/surefire-reports/TEST-*.xml'
#          reporter: java-junit
      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Tests Results Chrome_Linux"
          files: |
            target/surefire-reports/TEST-*.xml

  E2E_Firefox_Linux_Test:
    runs-on: ubuntu-latest
    needs: preprocess
    if: contains(needs.preprocess.outputs.selected, 'firefox')
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="firefox" -DexecutionAddress="local" -DtargetOperatingSystem="LINUX" -DheadlessExecution="true" -DwhenToTakePageSourceSnapshot="FailuresOnly" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -Dtest="${{ github.event.inputs.testsPath }}"
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Firefox_Linux_Allure
          path: "allure-report/*_AllureReport.html"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Firefox_Linux_Summary
          path: "execution-summary/ExecutionSummaryReport_*.html"
#      - name: Publish Report
#        continue-on-error: true
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Tests Report Firefox_Linux
#          path: 'target/surefire-reports/TEST-*.xml'
#          reporter: java-junit
      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Tests Results Firefox_Linux"
          files: |
            target/surefire-reports/TEST-*.xml
  E2E_Chrome_Mac_Test:
    runs-on: macos-latest
    needs: preprocess
    if: contains(needs.preprocess.outputs.selected, 'chrome')
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="chrome" -DexecutionAddress="local" -DtargetOperatingSystem="LINUX" -DheadlessExecution="true" -DwhenToTakePageSourceSnapshot="FailuresOnly" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -Dtest="${{ github.event.inputs.testsPath }}"
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Allure
          path: "allure-report/*_AllureReport.html"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Summary
          path: "execution-summary/ExecutionSummaryReport_*.html"
      #      - name: Publish Report
      #        continue-on-error: true
      #        uses: dorny/test-reporter@v1
      #        if: success() || failure()
      #        with:
      #          name: Tests Report Chrome_Linux
      #          path: 'target/surefire-reports/TEST-*.xml'
      #          reporter: java-junit
      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Tests Results Chrome_Linux"
          files: |
            target/surefire-reports/TEST-*.xml